// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnHhMvdr5ynptQUw8lWqKvx--xKrDxoys',
    appId: '1:831976547070:web:6539cfde648b1d99be3baf',
    messagingSenderId: '831976547070',
    projectId: 'biofarming-9859f',
    authDomain: 'biofarming-9859f.firebaseapp.com',
    databaseURL: 'https://biofarming-9859f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biofarming-9859f.appspot.com',
    measurementId: 'G-KZZVR8NLRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ0G4OEtoz4c5L0yoqkAGNGbuB4Suuezw',
    appId: '1:831976547070:android:8543fce6272edfe6be3baf',
    messagingSenderId: '831976547070',
    projectId: 'biofarming-9859f',
    databaseURL: 'https://biofarming-9859f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biofarming-9859f.appspot.com',
  );
}
